version: '3.8'

services:
  web:
    image: nginx:1.25-alpine
    container_name: ${PROJECT_NAME_QUA}_nginx
    ports:
      - "9090:80"
    environment:
      - PROJECT_NAME=${PROJECT_NAME_QUA}
    volumes:
      - "./www:/var/www/${PROJECT_NAME_QUA}:ro"
      - "./.docker/nginx/nginx.conf:/etc/nginx/conf.d/site.template:ro"
    command: sh -c "envsubst '$$PROJECT_NAME' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - qua-network

  php:
    environment:
      - DB_HOST=172.30.0.20
      - DB_PORT=3307
    build: ./.docker/php
    working_dir: /var/www/${PROJECT_NAME_QUA}
    container_name: ${PROJECT_NAME_QUA}_php
    volumes:
      - "./www:/var/www/${PROJECT_NAME_QUA}:ro"
    command: php-fpm
    networks:
      - qua-network

  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME_QUA}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./www/sql:/docker-entrypoint-initdb.d
    networks:
      qua-network:
        ipv4_address: 172.30.0.20

networks:
  qua-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
